### PR TITLE
♻️ code splitting

### PR DESCRIPTION
**Pull request by thrzl**
this pr splits the bot into a much simpler structure (no more 660 line file!) and adds cogs + jishaku. it also adds poetry as a dep manager to help keep better track of dependencies.

### CODE REVIEW

**Comment by ABadGame** [comment]
Sadly, we dont plan on using cogs.

**Comment by thrzl** [comment]
why is that? cogs add a lot of modularity, allow you to reload certain functionality and features, and also just help to organize the code (now you don't have to scroll around for the warn command, its just right in src/cogs/moderation)

**Comment by ABadGame** [comment]
They dont really seem to work for us

**Comment by thrzl** [comment]
how so?

**Comment by ABadGame** [comment]
Also, we can just ctrl+f to find stuff anyway

**Comment by thrzl** [comment]
that only solves one of the issues that cogs help with

**Comment by ABadGame** [comment]
yeah no sorry.

**Comment by ABadGame** [comment]
Will need updates due to the new level system thats about to be added.

**Pull request merged**
